services:
  # 1. Base de Datos PostgreSQL
  payment-db:
    image: postgres:15-alpine
    container_name: payment-postgres
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: hiberus
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiberus -d paymentdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Tu Microservicio Spring Boot
  payment-service:
    build: .
    container_name: payment-api
    ports:
      - "8080:8080"
    environment:
      # Conexi√≥n a la BD (usamos el nombre del servicio 'payment-db')
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: hiberus
      SPRING_DATASOURCE_PASSWORD: secretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      payment-db:
        condition: service_healthy

volumes:
  postgres_data: